### PR TITLE
version added to package.json

### PR DESCRIPTION
**Pull request by akialapiha**
Added the missing version property to the package.json

### CODE REVIEW

**Comment by maxisam** [comment]
The version will be add automatically from CI

**Comment by akialapiha** [comment]
Could you make a new release or at least tag this so we could use the hash version? The lint errors I fixed earlier are blocking us from using your module.

**Comment by maxisam** [comment]
I see. The change should be out today.

**Comment by maxisam** [comment]
it's 1.02 now

**Pull request closed without merging**
